### ISSUE TITLE
Can not work in the root directory of linux kernel

### ISSUE THREAD

**Issue by Rose1917** [rupran/kbuildparser#2]
Hi, thanks for your great tool first.
But I can not make it work when the target directory is the linux root directory. 

Like this,
![image](https://user-images.githubusercontent.com/49433992/191526749-55c79a31-beef-4136-b5b6-fdf427f5c900.png)
Meanwhile, when i specify the directory with some sub-directory, it can work normally. like this
![image](https://user-images.githubusercontent.com/49433992/191527003-cfaccea1-fc42-458c-874b-6ded644c390b.png)

* The Linux Source Kernel: 5.18.0
* The Root Makefile and the top kbuild file are attached as follow:

Looking for
[Kbuild&&Makefile.zip](https://github.com/rupran/kbuildparser/files/9617408/Kbuild.Makefile.zip)
ward to your response.

**Comment by rupran** [comment]
Hi, thank you for using my tool and reaching out.

I think this stems from the fact that you are not running `kbuildparser` from the root directory of the Linux source code and instead provide the root directory as a parameter. In this case, `kbuildparser` tries to parse the top-level Kbuild file as a regular Kbuild file (which it unfortunately is not) and fails to identify the directories to descend into.

So instead of running
```bash
/path/to/kbuildparser $ ./kbuildparser ../linux-5.18.10
```
you could try running it from the Linux directory without any parameters like this:
```bash 
/path/to/linux-5.18.10 $ ../kbuildparser/kbuildparser
```

Hope this helps!

**Comment by Rose1917** [comment]
Thanks for your prompt reply and your great work. I will try

**Comment by Rose1917** [comment]
It worked!
